version: 1.2
workflows:
- name: interpret-barcodes
  subclass: wdl
  primaryDescriptorPath: /interpret-barcodes.wdl
- name: run-incidence-regression
  subclass: wdl
  primaryDescriptorPath: /run-incidence-regression.wdl
- name: run-incidence-regression-update
  subclass: wdl
  primaryDescriptorPath: /run-incidence-regression-update.wdl
